# -*- coding: utf-8 -*-
"""colab 3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15OsF__tzjaCDE_-VC-Qme89qA1GynzAy

# Pronóstico de Ventas (Panel 3 - Series Temporales)

Este notebook contiene el pipeline de pronóstico para el proyecto SmartBazar.
Incluye agregación semanal, regresores (festivos y escolares), comparación de modelos (Prophet, Random Forest, XGBoost) y proyección a futuro.
"""

import pandas as pd
import numpy as np
from prophet import Prophet
from dateutil import parser
import holidays
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestRegressor
from xgboost import XGBRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_percentage_error

"""## 1. Carga y Limpieza de Datos"""

# Cargar datos
try:
    df_raw = pd.read_csv('ventas.csv', sep=';')
    print("Archivo 'ventas.csv' cargado correctamente.")
except FileNotFoundError:
    print("Error: No se encontró 'ventas.csv'. Asegúrate de subirlo a la sesión.")
    raise

# Algoritmo de normalización cronológica (resuelve ambigüedades día/mes)
def parsear_fechas_cronologicas(fechas):
    fechas_limpias = []
    fecha_anterior = pd.Timestamp.min
    for fecha_str in fechas:
        if pd.isna(fecha_str):
            fechas_limpias.append(pd.NaT)
            continue
        try:
            d1 = parser.parse(str(fecha_str), dayfirst=True)
            d2 = parser.parse(str(fecha_str), dayfirst=False)
            if d1 == d2:
                fecha_elegida = d1
            elif d1 >= fecha_anterior and d2 < fecha_anterior:
                fecha_elegida = d1
            elif d2 >= fecha_anterior and d1 < fecha_anterior:
                fecha_elegida = d2
            else:
                fecha_elegida = d1 if (d1 - fecha_anterior) < (d2 - fecha_anterior) else d2
            fechas_limpias.append(fecha_elegida)
            fecha_anterior = fecha_elegida
        except:
            fechas_limpias.append(pd.NaT)
    return fechas_limpias

if 'Fecha' in df_raw.columns and 'Total' in df_raw.columns:
    df_raw['Fecha_Estandar'] = pd.to_datetime(parsear_fechas_cronologicas(df_raw['Fecha']))
    df_raw.dropna(subset=['Fecha_Estandar'], inplace=True)
    fecha_inicio = pd.Timestamp(df_raw['Fecha_Estandar'].dt.normalize().min()).normalize()
    fecha_inicio = max(fecha_inicio, pd.Timestamp('2026-03-01'))
    fecha_fin = pd.Timestamp(df_raw['Fecha_Estandar'].dt.normalize().max()).normalize()
    df_raw = df_raw[(df_raw['Fecha_Estandar'].dt.normalize() >= fecha_inicio) & (df_raw['Fecha_Estandar'].dt.normalize() <= fecha_fin)].copy()
    df_raw['Fecha_Diaria'] = df_raw['Fecha_Estandar'].dt.normalize()
    print(f"Datos cargados: {len(df_raw)} registros.")
else:
    raise ValueError("Columnas incorrectas en ventas.csv. Se esperan 'Fecha' y 'Total'.")

"""## 2. Agregación Semanal y Regresores"""

# Agregación diaria y remuestreo semanal (Lunes)
ingreso_diario = df_raw.groupby('Fecha_Diaria')['Total'].sum().reset_index()
ingreso_diario.set_index('Fecha_Diaria', inplace=True)
full_range = pd.date_range(start=fecha_inicio, end=fecha_fin, freq='D')
ingreso_diario = ingreso_diario.reindex(full_range, fill_value=0)

weekly_df = ingreso_diario.resample('W-MON').sum().reset_index()
weekly_df.columns = ['ds', 'y']

# Regresores: Festivos y Periodos Escolares
pe_hols = holidays.country_holidays('PE', years=[2026])
hols_df = pd.DataFrame([{'ds': d, 'is_nat': 1} for d in pe_hols.keys()])
hols_df['ds'] = pd.to_datetime(hols_df['ds'])
school_dates = pd.date_range('2026-03-01', periods=30).union(pd.date_range('2026-07-20', periods=15))
school_df = pd.DataFrame({'ds': school_dates, 'is_school': 1})

def add_regressors(df):
    df = pd.merge(df, hols_df.set_index('ds').resample('W-MON').max().fillna(0), on='ds', how='left')
    df = pd.merge(df, school_df.set_index('ds').resample('W-MON').max().fillna(0), on='ds', how='left')
    return df.fillna(0)

weekly_df = add_regressors(weekly_df)
print(f"Datos semanales preparados: {len(weekly_df)} semanas.")

"""## 3. Preparación para Modelos de Regresión (Lags y Tiempo)"""

reg_df = weekly_df.copy()
for i in range(1, 4):
    reg_df[f'lag_{i}'] = reg_df['y'].shift(i)
reg_df['week'] = reg_df['ds'].dt.isocalendar().week.astype(int)
reg_df = reg_df.dropna()

features = ['is_nat', 'is_school', 'week', 'lag_1', 'lag_2', 'lag_3']
test_size = 4
train_reg, test_reg = reg_df[:-test_size], reg_df[-test_size:]
X_train, y_train = train_reg[features], train_reg['y']
X_test, y_test = test_reg[features], test_reg['y']

print(f"Train size: {len(train_reg)} semanas, Test size: {len(test_reg)} semanas.")

"""## 4. Entrenamiento y Evaluación de Modelos"""

# --- Prophet ---
train_p = weekly_df[:-test_size].copy()
train_p['y'] = np.log1p(train_p['y'])
m_prophet = Prophet(growth='linear', weekly_seasonality=False, yearly_seasonality=False)
m_prophet.add_regressor('is_nat'); m_prophet.add_regressor('is_school')
m_prophet.fit(train_p)
forecast_p_full = m_prophet.predict(weekly_df)
y_pred_p = np.expm1(forecast_p_full['yhat'][-test_size:]).clip(lower=0)

# --- Random Forest ---
rf = RandomForestRegressor(n_estimators=100, random_state=42)
rf.fit(X_train, y_train)
y_pred_rf = rf.predict(X_test)

# --- XGBoost ---
xgb = XGBRegressor(n_estimators=100, learning_rate=0.1, random_state=42)
xgb.fit(X_train, y_train)
y_pred_xgb = xgb.predict(X_test)

def get_metrics(true, pred):
    rmse = np.sqrt(mean_squared_error(true, pred))
    mape = mean_absolute_percentage_error(true.replace(0, 1), pred) * 100
    return rmse, mape

m_p = get_metrics(y_test, y_pred_p)
m_rf = get_metrics(y_test, y_pred_rf)
m_xgb = get_metrics(y_test, y_pred_xgb)

metrics_df = pd.DataFrame({
    'Modelo': ['Prophet', 'Random Forest', 'XGBoost'],
    'RMSE': [m_p[0], m_rf[0], m_xgb[0]],
    'MAPE (%)': [m_p[1], m_rf[1], m_xgb[1]]
})

display(metrics_df)

print("\nComponentes del pronóstico semanal (Prophet):")
m_prophet.plot_components(forecast_p_full)
plt.show()

plt.figure(figsize=(12, 6))
dates_test = test_reg['ds']
plt.plot(dates_test, y_test, 'ko-', label='Real', linewidth=2)
plt.plot(dates_test, y_pred_p, 'g--', label='Prophet')
plt.plot(dates_test, y_pred_rf, 'r--', label='Random Forest')
plt.plot(dates_test, y_pred_xgb, 'b--', label='XGBoost')
plt.title('Comparativa de Modelos: Ventana de Prueba')
plt.legend(); plt.grid(True); plt.show()

"""## 5. Benchmark y Análisis de Regresores"""

# Media Móvil Simple (3 semanas) como baseline
import joblib

# Media Móvil Simple (3 semanas) como baseline
window = 3
last_mean = train_reg['y'].tail(window).mean()
y_pred_ma = np.full(shape=test_size, fill_value=last_mean)
m_ma = get_metrics(y_test, y_pred_ma)

metrics_extended = pd.concat([metrics_df, pd.DataFrame({
    'Modelo': ['Media Móvil (3w)'],
    'RMSE': [m_ma[0]],
    'MAPE (%)': [m_ma[1]]
})], ignore_index=True)

print("Tabla de Métricas Extendida (incluyendo Benchmark):")
display(metrics_extended)

# Exportar parámetros de la Media Móvil
ma_model_params = {
    'window': window,
    'last_mean': last_mean
}
joblib.dump(ma_model_params, 'ma_model_params.joblib')
print("Parámetros de la Media Móvil 'ma_model_params.joblib' exportados correctamente.")

# Prophet sin regresores para evaluar impacto
m_prophet_base = Prophet(growth='linear', weekly_seasonality=False, yearly_seasonality=False)
train_p_base = weekly_df[:-test_size].copy()
train_p_base['y'] = np.log1p(train_p_base['y'])
m_prophet_base.fit(train_p_base)
forecast_p_base = m_prophet_base.predict(weekly_df)
y_pred_p_base = np.expm1(forecast_p_base['yhat'][-test_size:]).clip(lower=0)
m_p_base = get_metrics(y_test, y_pred_p_base)

metrics_final = pd.concat([metrics_extended, pd.DataFrame({
    'Modelo': ['Prophet Base (Sin Regresores)'],
    'RMSE': [m_p_base[0]],
    'MAPE (%)': [m_p_base[1]]
})], ignore_index=True)

print("Tabla de Métricas Final (Comparativa Completa):")
display(metrics_final)

plt.figure(figsize=(12, 6))
plt.plot(dates_test, y_test, 'ko-', label='Real', linewidth=2)
plt.plot(dates_test, y_pred_p, 'g--', label='Prophet (Con Regresores)', marker='s')
plt.plot(dates_test, y_pred_p_base, 'gray', linestyle=':', label='Prophet Base (Sin Regresores)', marker='x')
plt.title('Impacto de los Regresores (Feriados/Escolar) en Prophet')
plt.xlabel('Fecha'); plt.ylabel('Ventas')
plt.legend(); plt.grid(True, linestyle='--', alpha=0.7)
plt.show()

"""## 6. Pronóstico Futuro (Próximos 4 Periodos) con Prophet"""

import pandas as pd
import numpy as np
from prophet import Prophet
from dateutil import parser
import holidays
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestRegressor
from xgboost import XGBRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_percentage_error

# Re-entrenar Prophet con todos los datos
final_model = Prophet(growth='linear', weekly_seasonality=False, yearly_seasonality=False)
final_model.add_regressor('is_nat')
final_model.add_regressor('is_school')

df_full_p = weekly_df.copy()
df_full_p['y'] = np.log1p(df_full_p['y'])
final_model.fit(df_full_p)

future_dates_df = final_model.make_future_dataframe(periods=4, freq='W-MON')
future_dates_df = add_regressors(future_dates_df)
forecast_future = final_model.predict(future_dates_df)
forecast_future['yhat_original'] = np.expm1(forecast_future['yhat'])

# Calcular predicciones históricas completas para otros modelos (solo para visualización)
# Media Móvil (full historical)
y_pred_ma_full_plot = weekly_df['y'].rolling(window=3, min_periods=1).mean()

# Visualización mejorada con todos los modelos
plt.figure(figsize=(14, 7))
plt.plot(weekly_df['ds'], weekly_df['y'], 'ko-', label='Histórico Real', linewidth=2)

# Prophet's prediction for the entire historical period (from model trained on train data)
plt.plot(forecast_p_full['ds'], np.expm1(forecast_p_full['yhat']), 'g--', label='Prophet (Histórico)', alpha=0.7)

# Add predictions from other models for the test period
plt.plot(weekly_df['ds'], y_pred_ma_full_plot, 'c:', label='Media Móvil (Benchmark)', alpha=0.8)

# Future prediction from the final model (Prophet trained on all data)
last_historical_date = weekly_df['ds'].max()
idx_last_hist = forecast_future[forecast_future['ds'] == last_historical_date].index[0]

plt.plot(forecast_future.loc[idx_last_hist:, 'ds'], forecast_future.loc[idx_last_hist:, 'yhat_original'],
         'mP--', label='Prophet (Pronóstico Futuro)', linewidth=2)
plt.fill_between(forecast_future.loc[idx_last_hist:, 'ds'],
                 np.expm1(forecast_future.loc[idx_last_hist:, 'yhat_lower']),
                 np.expm1(forecast_future.loc[idx_last_hist:, 'yhat_upper']),
                 color='magenta', alpha=0.2, label='Intervalo de Confianza (Futuro)')

plt.title('Comparativa de Modelos y Pronóstico de Ventas')
plt.xlabel('Fecha'); plt.ylabel('Ventas Totales')
plt.legend(loc='upper left', bbox_to_anchor=(1,1), fontsize='small')
plt.grid(True, linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

import joblib

# Export the final model
joblib.dump(final_model, 'final_prophet_model.joblib')
print("Modelo 'final_prophet_model.joblib' exportado correctamente.")

import streamlit as st
import pandas as pd
import joblib
from prophet import Prophet
import holidays
import numpy as np
import matplotlib.pyplot as plt

st.set_page_config(layout='wide', page_title='Pronóstico de Ventas con Prophet')

st.title('Aplicación de Pronóstico de Ventas con Prophet')

# --- Cargar el Modelo --- #
@st.cache_resource
def load_prophet_model(model_path):
    try:
        model = joblib.load(model_path)
        return model
    except FileNotFoundError:
        st.error(f"Error: El archivo del modelo '{model_path}' no se encontró. Asegúrate de que está en la misma carpeta.")
        st.stop()

final_model = load_prophet_model('final_prophet_model.joblib')

# --- Definición de Regresores (debe coincidir con el entrenamiento) ---
# Asegúrate de que estas funciones y datos coincidan exactamente con cómo se entrenó el modelo
pe_hols = holidays.country_holidays('PE', years=[2026, 2027, 2028]) # Extiende los años según sea necesario
hols_df = pd.DataFrame([{'ds': d, 'is_nat': 1} for d in pe_hols.keys()])
hols_df['ds'] = pd.to_datetime(hols_df['ds'])

# Ajusta los rangos de fechas escolares según sea necesario
school_dates_2026 = pd.date_range('2026-03-01', periods=30).union(pd.date_range('2026-07-20', periods=15))
school_dates_2027 = pd.date_range('2027-03-01', periods=30).union(pd.date_range('2027-07-20', periods=15))
school_dates_2028 = pd.date_range('2028-03-01', periods=30).union(pd.date_range('2028-07-20', periods=15))

school_dates = school_dates_2026.union(school_dates_2027).union(school_dates_2028)
school_df = pd.DataFrame({'ds': school_dates, 'is_school': 1})

def add_regressors_streamlit(df):
    # Resample y merge para festivos
    hols_weekly = hols_df.set_index('ds').resample('W-MON').max().fillna(0).reset_index()
    df = pd.merge(df, hols_weekly, on='ds', how='left')

    # Resample y merge para escolares
    school_weekly = school_df.set_index('ds').resample('W-MON').max().fillna(0).reset_index()
    df = pd.merge(df, school_weekly, on='ds', how='left')

    return df.fillna(0)

# --- Sidebar para Configuración --- #
st.sidebar.header('Configuración del Pronóstico')
num_weeks = st.sidebar.slider('Número de semanas a pronosticar', 1, 52, 4)

# --- Generar Pronóstico --- #
if st.button('Generar Pronóstico'):
    # Obtener el historial del modelo para las fechas de inicio
    history_df = final_model.history.copy()
    history_df['ds'] = pd.to_datetime(history_df['ds'])

    future = final_model.make_future_dataframe(periods=num_weeks, freq='W-MON')
    future = add_regressors_streamlit(future)

    st.write(f"Pronosticando para las próximas {num_weeks} semanas...")

    forecast = final_model.predict(future)
    forecast['yhat_original'] = np.expm1(forecast['yhat']).clip(lower=0)
    forecast['yhat_lower_original'] = np.expm1(forecast['yhat_lower']).clip(lower=0)
    forecast['yhat_upper_original'] = np.expm1(forecast['yhat_upper']).clip(lower=0)

    # Visualización del Pronóstico
    st.subheader('Pronóstico de Ventas')
    fig = plt.figure(figsize=(12, 6))
    plt.plot(history_df['ds'], np.expm1(history_df['y']).clip(lower=0), 'k.', label='Ventas Históricas')
    plt.plot(forecast['ds'], forecast['yhat_original'], 'm-', label='Pronóstico Prophet', linewidth=2)
    plt.fill_between(forecast['ds'], forecast['yhat_lower_original'], forecast['yhat_upper_original'],
                     color='magenta', alpha=0.2, label='Intervalo de Confianza')
    plt.xlabel('Fecha')
    plt.ylabel('Ventas Totales')
    plt.title('Pronóstico de Ventas Semanales con Prophet')
    plt.legend()
    plt.grid(True)
    st.pyplot(fig)

    # Mostrar el pronóstico futuro en una tabla
    st.subheader('Detalle del Pronóstico Futuro')
    forecast_future_df = forecast[forecast['ds'] > history_df['ds'].max()][['ds', 'yhat_original', 'yhat_lower_original', 'yhat_upper_original']]
    forecast_future_df.columns = ['Fecha', 'Pronóstico', 'Límite Inferior', 'Límite Superior']
    forecast_future_df['Fecha'] = forecast_future_df['Fecha'].dt.date # Para una visualización más limpia
    st.dataframe(forecast_future_df.set_index('Fecha'))

st.markdown("""
### Cómo ejecutar esta aplicación:
1. Guarda el código anterior en un archivo llamado `app.py` en la misma carpeta donde está `final_prophet_model.joblib`.
2. Abre tu terminal o Anaconda Prompt.
3. Navega hasta la carpeta donde guardaste `app.py`.
4. Ejecuta el comando: `streamlit run app.py`
5. Se abrirá una pestaña en tu navegador web con la aplicación.
""")